---
- hosts: localhost
  connection: local
  become: true
  vars_files:
    - vars.yaml
  tasks:
  - name: Remove unwanted packages
    dnf:
      name:
      - gnome-boxes
      - gnome-calendar
      - gnome-classic-session
      - gnome-clocks
      - gnome-contacts
      - gnome-maps
      - gnome-photos
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-background-logo
      - gnome-shell-extension-horizontal-workspaces
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-places-menu
      - gnome-shell-extension-window-list
      - gnome-weather
      - rhythmbox
      state: absent
  - name: Upgrade all packages
    dnf:
      name: "*"
      state: latest
  - name: Install required packages
    dnf:
      name:
      - python3-lxml
      state: present
  - name: Enable rpmfusion
    dnf:
      name:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm
      state: present
  - name: Install GNOME apps
    dnf:
      name:
      - gnome-extensions-app
      - gnome-firmware
      - gnome-tweaks
      state: present
  - name: Install fonts
    dnf:
      name:
      - cascadia-code-fonts
      - google-noto-sans-fonts
      - google-roboto-fonts
      - liberation-fonts
      - overpass-fonts
      - redhat-display-fonts
      - redhat-text-fonts
  - name: Install development tools
    dnf:
      name:
      - copr-cli
      - golang
      - nodejs
      - "@Development Tools"
      - "@RPM Development Tools"
      state: present
  - name: Install container packages
    dnf:
      name:
      - buildah
      - podman
      - skopeo
      state: present
  - name: Install virtualization packages
    dnf:
      name:
      - libguestfs-tools
      - libvirt-client
      - virt-install
      - virt-manager
      - virt-viewer
      state: present
  - name: Allow users in the wheel group to manage libvirt
    template:
      src: templates/49-org.libvirt.unix.manager.rules.j2
      dest: /etc/polkit-1/rules.d/49-org.libvirt.unix.manager.rules
      owner: root
      group: root
      mode: 0644
  - name: Destroy and undefine default libvirt network
    virt_net:
      command: "{{item}}"
      name: default
    loop:
    - destroy
    - undefine
  - name: Define default libvirt network from template
    virt_net:
      command: define
      name: default
      xml: '{{ lookup("template", "templates/libvirt-network.xml.j2") }}'
  - name: Enable autostart for default libvirt network
    virt_net:
      name: default
      autostart: yes
  - name: Enable network access in /etc/libvirt/libvirtd.conf
    blockinfile:
      path: /etc/libvirt/libvirtd.conf
      insertafter: EOF
      block: |
        listen_tls = 0
        listen_tcp = 1
        auth_tcp = "none"
  - name: Enable libvirtd-tcp.socket
    systemd:
      name: libvirtd-tcp.socket
      enabled: yes
  - name: Add virbr0 to trusted firewall zone
    firewalld:
      zone: trusted
      interface: virbr0
      permanent: yes
      state: enabled
  - name: Enable nested kvm
    blockinfile:
      path: /etc/modprobe.d/kvm.conf
      create: yes
      block: |
        options kvm ignore_msrs=1
        options kvm_intel ept=1 nested=1 enable_apicv=1 enable_shadow_vmcs=1
  - name: Install miscellaneous packages
    dnf:
      name:
      - exfat-utils
      - firewall-config
      - fuse-exfat
      - gtk-v4l
      - hplip-gui
      - krb5-workstation
      - neofetch
      - pwgen
      - redhat-lsb
      - xclip
      - xdotool
      - youtube-dl
      - yubico-piv-tool
      - yubikey-manager
      - yubikey-personalization-gui
      state: present
  - name: Install Google Chrome
    dnf:
      name: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      state: present
  - name: Add Visual Studio Code repo
    yum_repository:
      name: code
      description: Visual Studio Code
      baseurl: https://packages.microsoft.com/yumrepos/vscode
      gpgkey: https://packages.microsoft.com/keys/microsoft.asc
      gpgcheck: yes
  - name: Install GPG key for Visual Studio Code repo
    rpm_key:
      key: https://packages.microsoft.com/keys/microsoft.asc
      state: present
  - name: Install Visual Studio Code
    dnf:
      name: code
      state: present
  - name: Add the flathub flatpak repo
    flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  - name: Install flatpaks
    flatpak:
      name: "{{item}}"
      state: present
      remote: flathub
    loop:
      - io.github.Hexchat
      - org.audacityteam.Audacity
      - org.gimp.GIMP
      - org.gnome.gitg
      - org.inkscape.Inkscape
  - name: Install cursor theme
    dnf:
      name: breeze-cursor-theme
      state: present
  - name: Add icon theme repo
    yum_repository:
      name: papirus-icon-theme
      description: Papirus Icon Theme
      baseurl: https://download.copr.fedorainfracloud.org/results/dirkdavidis/papirus-icon-theme/fedora-$releasever-$basearch/
      gpgkey: https://download.copr.fedorainfracloud.org/results/dirkdavidis/papirus-icon-theme/pubkey.gpg
      gpgcheck: yes
  - name: Install GPG key for icon theme repo
    rpm_key:
      key: https://download.copr.fedorainfracloud.org/results/dirkdavidis/papirus-icon-theme/pubkey.gpg
      state: present
  - name: Install icon theme
    dnf:
      name: papirus-icon-theme
      state: present
  - name: Add gnome and gtk theme repo
    yum_repository:
      name: flat-remix
      description: Flat Remix Theme
      baseurl: https://download.copr.fedorainfracloud.org/results/daniruiz/flat-remix/fedora-$releasever-$basearch/
      gpgkey: https://download.copr.fedorainfracloud.org/results/daniruiz/flat-remix/pubkey.gpg
      gpgcheck: yes
  - name: Install GPG key for gnome and gtk theme repo
    rpm_key:
      key: https://download.copr.fedorainfracloud.org/results/daniruiz/flat-remix/pubkey.gpg
      state: present
  - name: Install gnome and gtk theme
    dnf:
      name:
      - flat-remix-gnome
      - flat-remix-gtk
      state: present
  - name: Install media codecs
    dnf:
      name:
      - gstreamer1-libav
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-bad-free-gtk
      - gstreamer1-plugins-bad-freeworld
      - gstreamer1-plugins-base
      - gstreamer1-plugins-good
      - gstreamer1-plugins-ugly
      - gstreamer1-plugins-ugly-free
      state: present
  - name: Install packages for VA-API
    dnf:
      name:
      - gstreamer1-vaapi
      - intel-media-driver
      - libva
      - libva-intel-driver
      - libva-intel-hybrid-driver
      - libva-utils
      - libvdpau-va-gl
      state: present
  - name: Add user to groups
    user:
      name: "{{my_user}}"
      groups: mock
      append: yes
  - name: Enable fstrim.timer
    systemd:
      name: fstrim.timer
      enabled: yes

- hosts: localhost
  connection: local
  become: false
  vars_files:
    - vars.yaml
  tasks:
  - name: Set user.name in .gitconfig
    git_config:
      name: user.name
      scope: global
      value: "{{my_name}}"
  - name: Set user.email in .gitconfig
    git_config:
      name: user.email
      scope: global
      value: "{{my_email}}"
  - name: Create rpmbuild directories
    shell: mkdir -p $HOME/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    args:
      warn: no
  - name: Create .rpmmacros
    shell: echo '%_topdir %(echo $HOME)/rpmbuild' > $HOME/.rpmmacros
  - name: Install python packages
    pip:
      name: pylint
      extra_args: --user
  - name: Add gtk theme customization
    template:
      src: templates/gtk.css.j2
      dest: /home/{{my_user}}/.config/gtk-3.0/gtk.css
      owner: "{{my_user}}"
      group: "{{my_user}}"
      mode: 0644
